const DB_KEY = 'saxo_sample_database_v1';
const seed = {
  users: [
    { email: 'request@saxo.com', password: 'demo123', role: 'request' },
    { email: 'factory@saxo.com', password: 'demo123', role: 'factory' }
  ],
  masters: {
    names: ['Bhavana', 'Basker', 'Nagaraj'], dealers: ['Arun Distributors', 'Kaveri Traders'],
    customers: ['Aster Textiles', 'Nova Foods'], units: ['Chennai Unit', 'Bengaluru Unit'],
    locations: ['Chennai', 'Coimbatore', 'Bengaluru'], products: ['Classic Blend', 'Premium Mix', 'Natural Base']
  }, requests: [], notifications: []
};
let db = loadDB();
let currentUser = null;
let pendingSignup = null;
let activePage = 'home';

function loadDB() { try { return JSON.parse(localStorage.getItem(DB_KEY)) || structuredClone(seed); } catch { return structuredClone(seed); } }
function saveDB() { localStorage.setItem(DB_KEY, JSON.stringify(db)); }
function $(selector, root = document) { return root.querySelector(selector); }
function $$(selector, root = document) { return [...root.querySelectorAll(selector)]; }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2800); }

$$('[data-auth]').forEach(button => button.addEventListener('click', () => showAuth(button.dataset.auth)));
function showAuth(view) { ['signin','signup','otp'].forEach(v => $(`#${v}View`).hidden = v !== view); }
$('#signupForm').addEventListener('submit', e => {
  e.preventDefault(); const email=$('#signupEmail').value.trim().toLowerCase(), password=$('#signupPassword').value;
  if (!/^\S+@\S+\.\S+$/.test(email) || password.length < 6) { $('#signupError').textContent='Enter a valid email and a password of at least 6 characters.'; return; }
  if (db.users.some(u=>u.email===email)) { $('#signupError').textContent='An account with this email already exists.'; return; }
  pendingSignup={email,password,otp:String(Math.floor(100000+Math.random()*900000))}; $('#otpEmail').textContent=email; showAuth('otp'); toast(`Demo verification code: ${pendingSignup.otp}`);
});
$('#resendOtp').addEventListener('click',()=>{ if(pendingSignup){pendingSignup.otp=String(Math.floor(100000+Math.random()*900000));toast(`New demo code: ${pendingSignup.otp}`);} });
$('#otpForm').addEventListener('submit', e => {
  e.preventDefault(); if(!pendingSignup || $('#otpCode').value!==pendingSignup.otp){$('#otpError').textContent='That verification code is not correct.';return;}
  db.users.push({...pendingSignup,role:'request'}); delete db.users.at(-1).otp; saveDB(); $('#loginEmail').value=pendingSignup.email; pendingSignup=null; showAuth('signin'); toast('Account created. Please sign in.');
});
$('#signinForm').addEventListener('submit', e => {
  e.preventDefault(); const email=$('#loginEmail').value.trim().toLowerCase(), password=$('#loginPassword').value;
  const user=db.users.find(u=>u.email===email&&u.password===password); if(!user){$('#loginError').textContent='Email or password is incorrect.';return;} login(user);
});
function login(user){currentUser=user;$('#auth').hidden=true;$('#app').hidden=false;$('#userEmail').textContent=user.email;$('#userName').textContent=user.email.split('@')[0].replace(/^./,c=>c.toUpperCase());$('#avatar').textContent=user.email.slice(0,2).toUpperCase();$('#rolePill').textContent=user.role==='factory'?'Factory user':'Request user';$('#factoryNav').style.display=user.role==='factory'?'block':'none';renderPage('home');}
$('#logout').addEventListener('click',()=>{currentUser=null;$('#app').hidden=true;$('#auth').hidden=false;showAuth('signin');});
$('#menuButton').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')});
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
$('#closeMenu').addEventListener('click',closeMenu);$('#overlay').addEventListener('click',closeMenu);
$$('.nav-parent').forEach(b=>b.addEventListener('click',()=>b.parentElement.classList.toggle('open')));
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>{renderPage(b.dataset.page);closeMenu()}));
$('#notificationButton').addEventListener('click',()=>{ const items=db.notifications.filter(n=>currentUser.role==='factory'); toast(items.at(-1)?.message||'You are all caught up.'); });

const titles={home:'Overview',fill:'New sample request',view:'Sample requests',flow:'Sample flow',allocation:'Customer allocation',factory:'Manufacturing'};
function renderPage(page){activePage=page;$('#pageTitle').textContent=titles[page];$('#breadcrumb').textContent=`Workspace / ${titles[page]}`;$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const renders={home:renderHome,fill:renderFill,view:renderView,factory:renderFactory};(renders[page]||renderPlaceholder)();updateNotification();}
function updateNotification(){$('#notificationDot').classList.toggle('on',currentUser?.role==='factory'&&db.notifications.length>0)}
function renderHome(){
 const own=currentUser.role==='factory'?db.requests:db.requests.filter(r=>r.email===currentUser.email), pending=own.filter(r=>r.status==='Pending').length, progress=own.filter(r=>r.status==='In Progress').length;
 $('#page').innerHTML=`<div class="page-head"><div><h1>Good day, ${escapeHtml(currentUser.email.split('@')[0])}</h1><p>Here’s what’s happening with sample operations today.</p></div><button class="primary" data-go="fill">+ New sample request</button></div><div class="stats"><div class="stat-card"><i class="stat-icon">▱</i><span>Total requests</span><strong>${own.length}</strong><small>All recorded requests</small></div><div class="stat-card"><i class="stat-icon">◷</i><span>Pending</span><strong>${pending}</strong><small>Awaiting factory ETA</small></div><div class="stat-card"><i class="stat-icon">↗</i><span>In progress</span><strong>${progress}</strong><small>Being manufactured</small></div><div class="stat-card"><i class="stat-icon">✓</i><span>Completed</span><strong>0</strong><small>Ready for dispatch</small></div></div><div class="dashboard-grid"><div class="card"><div class="card-title"><h3>Recent activity</h3><button class="link-button" data-go="view">View all →</button></div>${own.length?own.slice(-4).reverse().map(r=>`<div class="activity"><div class="activity-icon">▱</div><div><p><strong>${r.ref}</strong> · ${escapeHtml(r.product)}</p><small>${formatDate(r.created)} · ${r.status}</small></div></div>`).join(''):'<div class="empty">No requests yet. Create your first sample request.</div>'}</div><div class="card"><div class="card-title"><h3>Quick actions</h3></div><div class="quick"><button data-go="fill">＋ &nbsp; Create sample request</button><button data-go="view">⌕ &nbsp; Browse all requests</button>${currentUser.role==='factory'?'<button data-go="factory">♜ &nbsp; Open manufacturing</button>':''}</div></div></div>`;
 bindGo();
}
function bindGo(){$$('[data-go]').forEach(b=>b.addEventListener('click',()=>renderPage(b.dataset.go)))}
function masterField(key,label,placeholder){return `<div class="field master-field" data-master="${key}"><label>${label} <b>*</b></label><div class="combo"><input list="list-${key}" name="${key}" placeholder="${placeholder}" autocomplete="off"><button type="button" class="add-master">+ Add new</button></div><datalist id="list-${key}">${db.masters[key].map(v=>`<option value="${escapeHtml(v)}">`).join('')}</datalist><small class="field-error"></small></div>`}
function renderFill(){
 $('#page').innerHTML=`<div class="page-head"><div><h1>Create sample request</h1><p>Complete the details below to send a new request to the factory.</p></div></div><div id="success" class="success-banner">✓ Sample Request Created Successfully.</div><form id="requestForm" class="card form-card" novalidate><h3 class="section-title">Requester details</h3><div class="form-grid"><div class="field"><label>Email <b>*</b></label><input class="readonly" name="email" value="${escapeHtml(currentUser.email)}" readonly><small class="field-error"></small></div><div class="field"><label>CC Mail <b>*</b></label><input name="cc" type="email" placeholder="colleague@company.com"><small class="field-error"></small></div>${masterField('names','Full Name','Search marketing person')}<div class="field"><label>Customer Type <b>*</b></label><div class="radio-group"><label class="radio-card"><input type="radio" name="customerType" value="Dealer"> Dealer</label><label class="radio-card"><input type="radio" name="customerType" value="Direct Customer"> Direct Customer</label></div><small class="field-error"></small></div><div id="customerField"></div></div><h3 class="section-title">Sample details</h3><div class="form-grid">${masterField('units','Unit Name','Search unit')}${masterField('locations','Location','Search location')}${masterField('products','Product Name','Search product')}<div class="field"><label>Sample Quantity <b>*</b></label><div class="quantity"><input name="quantity" type="number" min="0.01" step="0.01" placeholder="e.g. 1"><select name="quantityUnit"><option value="">Unit</option><option>KG</option><option>g</option><option>L</option><option>ml</option><option>pcs</option></select></div><small class="field-error"></small></div></div><div class="form-actions"><button class="secondary" type="reset">Clear</button><button class="primary" type="submit">Submit request →</button></div></form>`;
 bindMasterAdds(); $$('[name=customerType]').forEach(r=>r.addEventListener('change',()=>renderCustomerField(r.value))); const form=$('#requestForm'); form.addEventListener('submit',submitRequest); form.addEventListener('reset',()=>{ requestAnimationFrame(()=>{ $('#customerField').innerHTML=''; $$('.field-error',form).forEach(error=>error.textContent=''); }); });
}
function renderCustomerField(type){const key=type==='Dealer'?'dealers':'customers', label=type==='Dealer'?'Dealer Name':'Direct Customer Name';$('#customerField').outerHTML=`<div id="customerField">${masterField(key,label,`Search ${label.toLowerCase()}`)}</div>`;bindMasterAdds($('#customerField'));}
function bindMasterAdds(root=document){$$('.master-field',root).forEach(field=>{const button=$('.add-master',field); if(button.dataset.bound)return;button.dataset.bound='1';button.addEventListener('click',()=>{const key=field.dataset.master,input=$('input',field),value=prompt(`Add new ${$('label',field).textContent.replace('*','').trim()}:`)?.trim();if(!value)return;if(!db.masters[key].some(v=>v.toLowerCase()===value.toLowerCase())){db.masters[key].push(value);saveDB();const option=document.createElement('option');option.value=value;$('datalist',field).append(option);}input.value=value;toast(`${value} added to master data.`);});});}
function submitRequest(e){e.preventDefault();const form=e.currentTarget, data=new FormData(form);$$('.field-error',form).forEach(x=>x.textContent='');let valid=true;const require=(name,message)=>{const input=form.elements[name],value=data.get(name)?.trim();if(!value){const field=input instanceof RadioNodeList?input[0].closest('.field'):input.closest('.field');$('.field-error',field).textContent=message;valid=false;}return value};
 require('cc','Please enter CC Mail.');require('names','Please select Full Name.');const type=require('customerType','Please select Customer Type.');if(type==='Dealer')require('dealers','Please select Dealer Name.');if(type==='Direct Customer')require('customers','Please select Direct Customer Name.');require('units','Please select Unit Name.');require('locations','Please select Location.');require('products','Please select Product Name.');require('quantity','Please enter Sample Quantity.');require('quantityUnit','Please select a quantity unit.');if(data.get('cc')&&!/^\S+@\S+\.\S+$/.test(data.get('cc'))){form.elements.cc.closest('.field').querySelector('.field-error').textContent='Please enter a valid email address.';valid=false;}if(!valid)return;
 const now=new Date(), year=now.getFullYear(), number=String(db.requests.filter(r=>r.ref.startsWith(`SR-${year}`)).length+1).padStart(5,'0'),ref=`SR-${year}-${number}`;const request={id:crypto.randomUUID(),ref,created:now.toISOString(),email:currentUser.email,cc:data.get('cc'),fullName:data.get('names'),customerType:type,dealer:type==='Dealer'?data.get('dealers'):'',directCustomer:type==='Direct Customer'?data.get('customers'):'',unit:data.get('units'),location:data.get('locations'),product:data.get('products'),quantity:`${data.get('quantity')} ${data.get('quantityUnit')}`,status:'Pending',eta:''};db.requests.push(request);db.notifications.push({id:crypto.randomUUID(),requestId:request.id,message:`New Sample Request ${ref} has been created.`,created:now.toISOString()});saveDB();form.reset();$('#customerField').innerHTML='';$('#success').classList.add('show');window.scrollTo({top:0,behavior:'smooth'});toast(`${ref} submitted to Factory.`);
}
function formatDate(iso){return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso))}
function visibleRequests(){return currentUser.role==='factory'?db.requests:db.requests.filter(r=>r.email===currentUser.email)}
function renderView(){const rows=visibleRequests();$('#page').innerHTML=`<div class="page-head"><div><h1>Sample requests</h1><p>Track every request from submission through manufacturing.</p></div><button class="primary" data-go="fill">+ New request</button></div><div class="table-card"><div class="table-tools"><input id="tableSearch" placeholder="Search reference, product or customer..."><span class="role-pill">${rows.length} requests</span></div>${rows.length?`<table><thead><tr><th>REFERENCE</th><th>CREATED DATE & TIME</th><th>REQUESTED BY / CC</th><th>CUSTOMER</th><th>UNIT / LOCATION</th><th>PRODUCT</th><th>QUANTITY</th><th>STATUS</th></tr></thead><tbody>${rows.slice().reverse().map(requestRow).join('')}</tbody></table>`:'<div class="empty">No sample requests found.</div>'}</div>`;bindGo();$('#tableSearch')?.addEventListener('input',e=>$$('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(e.target.value.toLowerCase())));}
function requestRow(r){return `<tr><td><strong>${r.ref}</strong></td><td>${formatDate(r.created)}</td><td>${escapeHtml(r.email)}<br><small>CC: ${escapeHtml(r.cc)}</small></td><td>${escapeHtml(r.fullName)}<br><small>${r.customerType}: ${escapeHtml(r.dealer||r.directCustomer)}</small></td><td>${escapeHtml(r.unit)}<br><small>${escapeHtml(r.location)}</small></td><td>${escapeHtml(r.product)}</td><td>${escapeHtml(r.quantity)}</td><td><span class="status ${r.status==='Pending'?'pending':'progress'}">${r.status}</span></td></tr>`}
function renderFactory(){if(currentUser.role!=='factory'){renderPage('home');return;}const rows=db.requests;$('#page').innerHTML=`<div class="page-head"><div><h1>Factory manufacturing</h1><p>Review new requests and schedule expected completion dates.</p></div><span class="role-pill">Authorized factory access</span></div><div class="factory-list">${rows.length?rows.slice().reverse().map(r=>`<article class="factory-item"><div><h3>${r.ref}</h3><p>${formatDate(r.created)} · ${escapeHtml(r.email)}</p></div><div class="factory-details"><span>CUSTOMER<strong>${escapeHtml(r.dealer||r.directCustomer)}</strong></span><span>PRODUCT<strong>${escapeHtml(r.product)}</strong></span><span>QUANTITY<strong>${escapeHtml(r.quantity)}</strong></span><span>STATUS<strong><em class="status ${r.status==='Pending'?'pending':'progress'}">${r.status}</em></strong></span></div><div class="eta-control"><label>FACTORY ETA<input type="date" value="${r.eta||''}" min="${new Date().toISOString().slice(0,10)}" data-eta="${r.id}"></label><button class="primary" data-save-eta="${r.id}">Save</button></div></article>`).join(''):'<div class="card empty">No requests are waiting for manufacturing.</div>'}</div>`;$$('[data-save-eta]').forEach(b=>b.addEventListener('click',()=>{const r=db.requests.find(x=>x.id===b.dataset.saveEta),value=$(`[data-eta="${r.id}"]`).value;if(!value){toast('Please choose an ETA date.');return;}r.eta=value;r.status='In Progress';saveDB();toast(`${r.ref} is now In Progress.`);renderFactory();}));}
function renderPlaceholder(){ $('#page').innerHTML=`<div class="card placeholder"><div>◫</div><h2>${titles[activePage]}</h2><p>This module is ready for the next stage of your application.</p></div>`; }
